site_name: pyclugen documentation
site_url: https://clugen.github.io/pyclugen
repo_url: https://github.com/clugen/pyclugen
edit_uri: https://github.com/clugen/pyclugen/edit/master/docs/docs/
site_description: Documentation for the pyclugen cluster generation toolbox
site_author: Nuno Fachada

theme:
  name: "material"
  logo: https://github.com/clugen/.github/blob/main/logos/apple-touch-icon-120x120.png?raw=true
  favicon: https://raw.githubusercontent.com/clugen/.github/main/logos/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        selection:
          docstring_style: google
        rendering:
          show_root_toc_entry: false
          show_submodules: no
          heading_level: 2
          line_length: 80
          show_signature_annotations: true
          separate_signature: true
    watch:
    - ../clugen

nav:
- Home: index.md
- Theory: theory.md
- Examples: examples.md
- API: api.md
- Development: dev.md

markdown_extensions:
- admonition
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
    guess_lang: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.arithmatex:
    generic: true
- toc:
    toc_depth: 2

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
