site_name: pyclugen documentation
theme:
  name: "material"

plugins:
- search
# - gen-files:
#     scripts:
#     - gen_ref_pages.py
# - section-index
# - literate-nav:
#     nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          docstring_style: google
        rendering:
          show_submodules: no
    watch:
      - ../clugen
#      - gen_ref_pages.py

nav:
- Home: index.md
- API: api.md

