site_name: pyclugen documentation
theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          docstring_style: google
        rendering:
          show_submodules: no
          heading_level: 2
    watch:
      - ../clugen

nav:
- Home: index.md
- API: api.md

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
